# Generated by Django 3.0.3 on 2021-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiSaco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='pesoactual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
