# Generated by Django 3.0.3 on 2021-03-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiSaco', '0004_auto_20210310_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='operador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ServiSaco.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
