# Generated by Django 3.0.3 on 2021-03-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiSaco', '0007_remove_pedido_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='operador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ServiSaco.Usuario'),
            preserve_default=False,
        ),
    ]
