# Generated by Django 3.0.3 on 2021-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiSaco', '0008_pedido_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='operador',
            field=models.CharField(max_length=30),
        ),
    ]
