# Generated by Django 3.0.3 on 2021-03-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiSaco', '0009_auto_20210310_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='operador',
        ),
    ]
